# Generated by Django 4.2.3 on 2023-07-30 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cimg', models.CharField(blank=True, max_length=50)),
                ('ccount', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ussr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.TextField(blank=True)),
                ('pslug', models.CharField(blank=True, max_length=100)),
                ('pprice', models.CharField(blank=True, max_length=100)),
                ('pimg', models.CharField(blank=True, max_length=100)),
                ('pcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.category')),
            ],
        ),
    ]
